import type { Metadata } from "next";
import { Lexend } from 'next/font/google';
import './globals.css';
import 'react-phone-input-2/lib/style.css';


export const metadata: Metadata = {
  title: "Tatheer",
  description: "Generated by create next app",
};
const lexend = Lexend({
  subsets: ['latin'],
  weight: ['400', '500', '700', '900'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en" className={lexend.className}>
      <body  className="font-lexend">
        {children}
      </body>
    </html>
  );
}
